#
# Authors: Wouter Van Gansbeke & Simon Vandenhende
# Licensed under the CC BY-NC 4.0 license (https://creativecommons.org/licenses/by-nc/4.0/)

# Seed
seed: 3

# Dataset
train_db_name: cityscapes
use_gt_masks: True      # masks mined from ground-truth labels
train_db_kwargs:
   saliency: saliency_basnet_tiny
   saliency_gt: saliency_mined_masks_100_seed3
   n_gt_images: 100
   load_unsup: True # use only supervised masks (False) or supervised + unsupervised (True)
train_db2_name: null
train_db2_kwargs:
   saliency: null
num_workers: 8
train_batch_size: 64

# Model
backbone: mobilenetv3
backbone_kwargs:  # not uset
   dilated: True
   pretraining: imagenet_classification  
model_kwargs:
   ndim: 32
   head: linear   # not used
   upsample: True
   use_classification_head: True # not used
head: lraspp
# Freeze block 1 and 2 in backbone (~1% miou improvement)
# NOTE cannot freeze layers with the current function (utils.utils.py) when single_thread
freeze_layers: False 
load_checkpoint: False
#my_checkpoint: /home/danmoral/MaskContrast/pretrain/outputs/ckpt_mask_pt_CS_no_IN_199.tar


# Optimizer
epochs: 600 #40   -- set to 600 so that the poy scheduler does not impact that much
optimizer: sgd
optimizer_kwargs:
   lr: 0.004
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly

# MoCo
moco_kwargs:
   T: 0.5 # Temperature
   m: 0.999 # Momentum
   K: 128 # Negatives
